### ISSUE TITLE
ENH: secret key match method(s)

### ISSUE THREAD

**Issue by westurner** [volleybus/Wireguard-Vanity-Key-Searcher#4]
It might be useful to instead/also specify startswith/contains constraints for the private key.

This would require changing or extending the `-m/--matchmethod` argument or adding additional arguments for private key constraints.

**Comment by volleybus** [comment]
Since 25519 accepts any string as a private key, simply a random b64 string with the target at the beginning that is 32 bytes long would suffice I believe. So instead of generating a random and checking against the target, building the key around the target should be cheaper. So much cheaper that even multithreading is not worth it. 

Here's an example:


```python
def private_keygen(target):
    from secrets import choice

    private_candidate = target
    for _ in range(43 - len(target)):
        private_candidate += choice(lexicon)
    private_candidate += "="
    # at this point the b64 of the key may be misaligned, yet it does not matter.
    private = PrivateKey(private_key=b64decode(private_candidate.encode("ascii")))
    return b64encode(bytes(private)).decode("ascii"), b64encode(bytes(private.public_key)).decode("ascii")

```
But I do not see the use for a vanity private key, all it does is it reduces your degree of freedom and hence security.
